version: '3.8'

services:
  mongodb:
    image: 'mongo:5.0'
    container_name: 'mongo-container'
    environment:
      - MONGO_INITDB_DATABASE=Bicycle
      - MONGO_INITDB_ROOT_USERNAME=app
      - MONGO_INITDB_ROOT_PASSWORD=bicycle
    volumes:
      - ./db-data:/data/db
    ports:
      - '27017-27019:27017-27019'

  php:
    build:
      context: .
      target: app_php
    image: sf-docker/php:dev
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
      PHP_DATE_TIMEZONE: ${PHP_DATE_TIMEZONE:-UTC}
      XDEBUG_CONFIG: remote_host=127.0.0.1
      PHP_IDE_CONFIG: serverName=localhost
    depends_on:
      - mongodb
    volumes:
      - .:/app:rw,cached
      - var:/app/var

  nginx:
    build:
      context: .
      target: app_nginx
    image: sf-docker/nginx:dev
    ports:
      - "8080:80"
    depends_on:
      - php
    volumes:
      - ./public:/app/public:ro

volumes:
  db-data:
  var: