version: '3.8'

services:
  mongodb:
    container_name: database
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=bicycle
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./db-data:/data/db
    ports:
      - '27017-27019:27017-27019'

  php:
    container_name: php
    build:
      context: ./php-fpm
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
      PHP_DATE_TIMEZONE: ${PHP_DATE_TIMEZONE:-UTC}
      XDEBUG_CONFIG: remote_host=127.0.0.1
      PHP_IDE_CONFIG: serverName=localhost
    ports:
      - '9000:9000'
    depends_on:
      - database
    volumes:
      - ../.:/var/www/bicycle

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - ../.:/var/www/bicycle:ro
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database

volumes:
  db-data:
  var: